apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.headlessName" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: plaintext-host
      port: 9092
      targetPort: 9092
    - name: plaintext
      port: 19092
      targetPort: 19092
    - name: controller
      port: 29093
      targetPort: 29093
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
