apiVersion: v2
name: rocketchat
description: Rocket.Chat via official upstream chart (naphtha defaults)
type: application
version: 1.0.1
appVersion: "8.3.2"

dependencies:
  - name: rocketchat
    version: 6.32.1
    repository: https://rocketchat.github.io/helm-charts
