apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:AndreaTrendafilov/naphtha-charts.git
        revision: main
        files:
          - path: deployments/apps/**/config.yaml
          - path: deployments/apps/**/values.yaml
          - path: apps/**/config.yaml
          - path: apps/**/values.yaml
  template:
    metadata:
      name: "{{app.name}}-{{app.environment}}"
      labels:
        name: "{{app.name}}-{{app.environment}}"
        environment: "{{app.environment}}"
        namespace: "{{app.namespace}}"
        os: "{{app.os}}"
    spec:
      project: "{{app.project}}"
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: false
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: "{{chart.repoURL}}"
        targetRevision: "{{chart.version}}"
        path: "{{chart.path}}"
        helm:
          valueFiles:
            - "{{chart.valueFiles}}"
      destination:
        server: "{{app.cluster}}"
        namespace: "{{app.namespace}}"
