apiVersion: v2
name: k8ssandra-operator
description: Umbrella over upstream `k8ssandra-operator` (naphtha defaults)
type: application
version: 1.0.0
appVersion: "1.31.0"

dependencies:
  - name: k8ssandra-operator
    version: "1.31.0"
    repository: "https://helm.k8ssandra.io/stable"
