apiVersion: v2
name: kube-prometheus-stack
description: Umbrella over upstream `kube-prometheus-stack` (naphtha defaults)
type: application
version: 1.0.0
appVersion: "83.5.1"

dependencies:
  - name: kube-prometheus-stack
    version: "83.5.1"
    repository: "https://prometheus-community.github.io/helm-charts"
