app:
  project: apps
  environment: prod
  name: rocketchat
  os: Linux
  cluster: https://kubernetes.default.svc
  namespace: rocketchat
chart:
  repoURL: git@github.com:AndreaTrendafilov/naphtha-charts.git
  path: charts/rocketchat
  version: main
  valueFiles: ../../apps/rocketchat/values.yaml
