# Customize Rocket.Chat deployment for prod
rocketchat:
  ingress:
    hosts:
      - host: "chat.naphtha.dev"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: rocketchat-tls
        hosts:
          - "chat.naphtha.dev"

  persistence:
    storageClass: ""
    size: 20Gi

  mongodb:
    auth:
      rootPassword: "CHANGE_ME_root"
      passwords:
        - "CHANGE_ME_password"
