apiVersion: v2
name: cert-manager
description: Umbrella over upstream `cert-manager` (naphtha defaults)
type: application
version: 1.0.0
appVersion: "v1.20.2"

dependencies:
  - name: cert-manager
    version: "v1.20.2"
    repository: "https://charts.jetstack.io"
