image:
  repository: ghcr.io/wg-easy/wg-easy
  # tag: latest

env:
  WG_HOST: wg.naphtha.dev
  # PASSWORD_HASH: ""  # optional: bcrypt admin password hash

service:
  type: NodePort
  ports:
    wireguard:
      port: 51820
      protocol: UDP
      nodePort: 51820
    http:
      port: 51821
      protocol: TCP
      nodePort: 31821

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: wg.naphtha.dev
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: wg-easy
              port:
                number: 51821
  tls:
    - secretName: wg-easy-tls
      hosts:
        - wg.naphtha.dev

persistence:
  enabled: true
  size: 1Gi
