replicaCount: 1

image:
  registry: ghcr.io
  repository: wg-easy/wg-easy
  tag: "15.1.0"
  pullPolicy: IfNotPresent

service:
  # Ports exposed by the container (used in deployment.yaml)
  vpnPort: 51820 # UDP (WireGuard)
  webPort: 51821 # TCP (wg-easy UI)

  # WireGuard UDP Service (LoadBalancer)
  wireguard:
    enabled: true
    type: LoadBalancer
    externalTrafficPolicy: Local
    port: 51825 # service port
    targetPort: 51820 # pod target port
    annotations: {} # e.g. external-dns.alpha.kubernetes.io/hostname: vpn.naphtha.dev
  commonAnnotations: {}

  # Web UI Service (fronted by Ingress)
  ui:
    enabled: true
    type: ClusterIP
    port: 51840 # service port
    targetPort: 51821 # pod target port
    # nodePort: 8080       # only if type: NodePort
    annotations: {}
    externalTrafficPolicy: ClusterIP # harmless for ClusterIP

ingress:
  enabled: true
  className: "traefik"
  hostname: "ui.vpn.naphtha.dev"
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  tls:
    - secretName: wg-easy-tls
      hosts:
        - "ui.vpn.naphtha.dev"
  # extraHosts:
  #   - host: "alt-ui.vpn.naphtha.dev"
  #     path: "/"

persistence:
  enabled: true
  size: 1Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: "local-path"

# wg-easy unattended setup (deployment.yaml envs)
init:
  enabled: true
  username: "admin"
  password: "CHANGE_ME_superstrong"

# WireGuard server & peer defaults (deployment.yaml envs)
wireguardConfig:
  host: "vpn.naphtha.dev"
  defaultDns: "1.1.1.1,8.8.8.8"
  subnet: "10.10.0.0/24"
  ipv6Subnet: ""
  # allowedIPs: "0.0.0.0/0, ::/0"

# Kernel/sysctl (deployment.yaml initContainer)
sysctls:
  - name: net.ipv4.conf.all.src_valid_mark
    value: "1"
  - name: net.ipv4.ip_forward
    value: "1"

securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
