apiVersion: v2
name: redis
description: Redis using the official Docker Hub image (not Bitnami)
type: application
version: 1.0.1
appVersion: "8.4.2"
home: https://redis.io/
sources:
  - https://hub.docker.com/_/redis
  - https://github.com/redis/redis
